import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Header from "@/components/common/Header";
import { MessagesContext } from "@/context/MessagesContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <MessagesContext.Provider
            value={{ messages: [], setMessages: () => {} }}
          >
            <Header />

            {children}
          </MessagesContext.Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
