import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Header from "@/components/common/Header";
import PromptUserProvider from "@/providers/prompt-provider";
import AuthProvider from "@/providers/auth-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { ConvexClientProvider } from "@/providers/convez-client-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>
            <GoogleOAuthProvider
              clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
            >
              <PromptUserProvider>
                <AuthProvider>
                  <Header />

                  {children}
                </AuthProvider>
              </PromptUserProvider>
            </GoogleOAuthProvider>
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
