import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Header from "@/components/common/Header";
import PromptUserProvider from "@/providers/prompt-provider";
import AuthProvider from "@/providers/auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <PromptUserProvider>
            <AuthProvider>
              <Header />

              {children}
            </AuthProvider>
          </PromptUserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
